export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_DATA_SUMMARY = "GET_DATA_SUMMARY";
export const GET_PROTOCOL = "GET_PROTOCOL";
export const CLEAR_PROTOCOL = "CLEAR_PROTOCOL";

export const SET_PROTOCOL_HEADER = "SET_PROTOCOL_HEADER";
export const SET_PROTOCOL_INVESTIGATORS = "SET_PROTOCOL_INVESTIGATORS";
export const SET_PROTOCOL_DATES = "SET_PROTOCOL_DATES";
export const SET_PROTOCOL_VICTIM = "SET_PROTOCOL_VICTIM";
export const SET_PROTOCOL_CIRCUMSTANCES = "SET_PROTOCOL_CIRCUMSTANCES";
export const SET_PROTOCOL_CAUSES = "SET_PROTOCOL_CAUSES";
export const SET_PROTOCOL_FAULT = "SET_PROTOCOL_FAULT";
export const SET_PROTOCOL_EFFECTS = "SET_PROTOCOL_EFFECTS";
export const SET_PROTOCOL_TYPES = "SET_PROTOCOL_TYPES";
export const SET_PROTOCOL_RECOMMENDATIONS = "SET_PROTOCOL_RECOMMENDATIONS";
export const SET_PROTOCOL_OBSTACLES = "SET_PROTOCOL_OBSTACLES";
export const SET_PROTOCOL_ATTACHMENTS = "SET_PROTOCOL_ATTACHMENTS";
export const SET_PROTOCOL_FINISH = "SET_PROTOCOL_FINISH";



