export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SET_PROTOCOL_HEADER = "SET_PROTOCOL_HEADER";
export const SET_PROTOCOL_INVESTIGATORS = "SET_PROTOCOL_INVESTIGATORS";
export const SET_PROTOCOL_DATES = "SET_PROTOCOL_DATES";

export const CLEAR_PROTOCOL = "CLEAR_PROTOCOL";


